name: Sync Blogfa Posts
on:
  schedule:
    # Runs every hour (you can change this cron timing if needed)
    - cron: '0 * * * *'
  workflow_dispatch: # Allows you to manually trigger it anytime

jobs:
  update-readme:
    name: Update this repo's README with latest stories
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Pull blog posts
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          # REPLACE WITH YOUR ACTUAL BLOGFA FEED URL:
          feed_list: "http://mahouarchive.blogfa.com/rss"
          max_post_count: 5
